# Site settings
title: Photographe Paris - DMG
email: "contact@dmg-photographer.com"
description: "Photographe Paris et r&eacute;gion parisienne. Prestations book comédien, shootings, mariages, particuliers"
og_description: "Photographe Paris et r&eacute;gion parisienne. Prestations book comédien, shootings, mariages, particuliers"
baseurl: ""
url: ""
currentyear: 2020
facebook_username:
instagram_username: "dmgphotographer"

# Owner/author information
owner:
  name: DMG
  favicon: favicon.png
  info: Portfolio DMG

  # Internal nav
nav:
  - COMEDIENS/PORTRAITS: "galerie_portraits/"
  - MODE: "galerie_mode/"
  - BEAUTY: "galerie_beauty/"
  - OTHERS: "galerie_others/"
  - MARIAGE: "galerie_mariage/"
  - ABOUT: "about/"

 # All translation keys
translations:
 # 404.html
  permalink: "/404.html"

 # Build settings
markdown: kramdown
exclude: ["README.md"]

sass:
  style: compressed
